// palette.js — Mard 拼豆色板数据（标准 211 色 + 15色大地系 = 221色）
// 按 Mard 官方色卡分组：A黄橙26色 B绿色32色 C蓝青29色 D蓝色26色
// E粉玫24色 F红色25色 G棕肤21色 H黑白23色 M大地15色
// hex 值为近似参考色，请以实物色卡为准

const MARD_PALETTE = [
    // ==========================================
    //  A 系列 · 黄橙系（A01 ~ A26）
    // ==========================================
    { id: "A01", name: "白色", hex: "#FFFFFF" },
    { id: "A02", name: "奶白", hex: "#FDF5E6" },
    { id: "A03", name: "米黄", hex: "#FAE6B1" },
    { id: "A04", name: "浅黄", hex: "#FFF176" },
    { id: "A05", name: "柠黄", hex: "#FFEE58" },
    { id: "A06", name: "明黄", hex: "#FFD600" },
    { id: "A07", name: "橙黄", hex: "#FFAB00" },
    { id: "A08", name: "橘色", hex: "#FF8F00" },
    { id: "A09", name: "深橘", hex: "#EF6C00" },
    { id: "A10", name: "橘红", hex: "#E65100" },
    { id: "A11", name: "鹅黄", hex: "#FFF9C4" },
    { id: "A12", name: "杏色", hex: "#FBCEB1" },
    { id: "A13", name: "芥黄", hex: "#DFAF2C" },
    { id: "A14", name: "土黄", hex: "#CC8833" },
    { id: "A15", name: "琥珀", hex: "#E8A317" },
    { id: "A16", name: "奶油黄", hex: "#FFF8DC" },
    { id: "A17", name: "柠檬奶油", hex: "#FFF2A8" },
    { id: "A18", name: "蜜桃色", hex: "#FFDAB9" },
    { id: "A19", name: "浅杏", hex: "#FFE4C4" },
    { id: "A20", name: "焦糖", hex: "#BF360C" },
    { id: "A21", name: "荧光黄", hex: "#CCFF00" },
    { id: "A22", name: "荧光橙", hex: "#FF5F15" },
    { id: "A23", name: "荧光黄绿", hex: "#7FFF00" },
    { id: "A24", name: "透明黄", hex: "#FFF8B0" },
    { id: "A25", name: "透明金黄", hex: "#FFDF6B" },
    { id: "A26", name: "透明橙", hex: "#FFB86B" },

    // ==========================================
    //  B 系列 · 绿色系（B01 ~ B32）
    // ==========================================
    { id: "B01", name: "浅绿", hex: "#C8E6C9" },
    { id: "B02", name: "草绿", hex: "#81C784" },
    { id: "B03", name: "翠绿", hex: "#4CAF50" },
    { id: "B04", name: "深绿", hex: "#2E7D32" },
    { id: "B05", name: "墨绿", hex: "#1B5E20" },
    { id: "B06", name: "薄荷", hex: "#80CBC4" },
    { id: "B07", name: "嫩绿", hex: "#AED581" },
    { id: "B08", name: "柠绿", hex: "#C0CA33" },
    { id: "B09", name: "橄榄", hex: "#9E9D24" },
    { id: "B10", name: "湖水绿", hex: "#66CDAA" },
    { id: "B11", name: "松石绿", hex: "#40C9B0" },
    { id: "B12", name: "苔绿", hex: "#6B8E4E" },
    { id: "B13", name: "黄绿", hex: "#9ACD32" },
    { id: "B14", name: "军绿", hex: "#4B5320" },
    { id: "B15", name: "松针绿", hex: "#1C6B3A" },
    { id: "B16", name: "浅薄荷", hex: "#C5F0E0" },
    { id: "B17", name: "抹茶绿", hex: "#C8E6A0" },
    { id: "B18", name: "浅草绿", hex: "#B2E5A0" },
    { id: "B19", name: "柳绿", hex: "#CCE698" },
    { id: "B20", name: "奶绿", hex: "#ACE1AF" },
    { id: "B21", name: "深松绿", hex: "#1E4D3A" },
    { id: "B22", name: "深苔绿", hex: "#3D5229" },
    { id: "B23", name: "暗橄榄", hex: "#4A5528" },
    { id: "B24", name: "荧光绿", hex: "#39FF14" },
    { id: "B25", name: "荧光薄荷", hex: "#00FF7F" },
    { id: "B26", name: "荧光柠绿", hex: "#76FF03" },
    { id: "B27", name: "透明浅绿", hex: "#A8E0A8" },
    { id: "B28", name: "透明绿", hex: "#78C878" },
    { id: "B29", name: "透明深绿", hex: "#509850" },
    { id: "B30", name: "透明薄荷", hex: "#88DEB8" },
    { id: "B31", name: "珠光绿", hex: "#68A880" },
    { id: "B32", name: "闪光绿", hex: "#40A848" },

    // ==========================================
    //  C 系列 · 蓝青系（C01 ~ C29）
    // ==========================================
    { id: "C01", name: "天青", hex: "#80DEEA" },
    { id: "C02", name: "青色", hex: "#26A69A" },
    { id: "C03", name: "蓝绿", hex: "#00897B" },
    { id: "C04", name: "冰蓝", hex: "#B3E5FC" },
    { id: "C05", name: "矢车菊蓝", hex: "#6495ED" },
    { id: "C06", name: "灰蓝", hex: "#7B9DB7" },
    { id: "C07", name: "粉蓝", hex: "#B0D4F1" },
    { id: "C08", name: "婴儿蓝", hex: "#A2CFFE" },
    { id: "C09", name: "浅天蓝", hex: "#B0E0E6" },
    { id: "C10", name: "水蓝", hex: "#ADD8E6" },
    { id: "C11", name: "深湖蓝", hex: "#005F6B" },
    { id: "C12", name: "暗青", hex: "#005566" },
    { id: "C13", name: "深钴蓝", hex: "#003A6C" },
    { id: "C14", name: "荧光青", hex: "#00FFFF" },
    { id: "C15", name: "荧光天蓝", hex: "#00BFFF" },
    { id: "C16", name: "透明浅蓝", hex: "#A8D4F0" },
    { id: "C17", name: "透明天蓝", hex: "#8DD8E8" },
    { id: "C18", name: "透明青", hex: "#7BC8C0" },
    { id: "C19", name: "透明蓝绿", hex: "#68B8B0" },
    { id: "C20", name: "珠光天蓝", hex: "#A0C0E0" },
    { id: "C21", name: "闪光青", hex: "#38A8A0" },
    { id: "C22", name: "闪光天蓝", hex: "#58A8E0" },
    { id: "C23", name: "夜光青", hex: "#C0E8E0" },
    { id: "C24", name: "夜光天蓝", hex: "#B8D8F0" },
    { id: "C25", name: "夜光蓝", hex: "#C8D8F0" },
    { id: "C26", name: "透明", hex: "#EDF0F5" },
    { id: "C27", name: "珠光白", hex: "#F0EEF0" },
    { id: "C28", name: "闪光白", hex: "#F8F8FF" },
    { id: "C29", name: "闪光银", hex: "#C8C8D0" },

    // ==========================================
    //  D 系列 · 蓝色系（D01 ~ D26）
    // ==========================================
    { id: "D01", name: "浅蓝", hex: "#BBDEFB" },
    { id: "D02", name: "天蓝", hex: "#64B5F6" },
    { id: "D03", name: "湖蓝", hex: "#42A5F5" },
    { id: "D04", name: "宝蓝", hex: "#1E88E5" },
    { id: "D05", name: "深蓝", hex: "#1565C0" },
    { id: "D06", name: "藏青", hex: "#0D47A1" },
    { id: "D07", name: "石板蓝", hex: "#5C6BC0" },
    { id: "D08", name: "靛蓝", hex: "#3F51B5" },
    { id: "D09", name: "海军蓝", hex: "#283593" },
    { id: "D10", name: "钴蓝", hex: "#0047AB" },
    { id: "D11", name: "浅薰衣草", hex: "#E6E6FA" },
    { id: "D12", name: "午夜蓝", hex: "#191970" },
    { id: "D13", name: "深海蓝", hex: "#0C2340" },
    { id: "D14", name: "墨蓝", hex: "#1C2841" },
    { id: "D15", name: "荧光蓝", hex: "#4D4DFF" },
    { id: "D16", name: "透明蓝", hex: "#7BB8E0" },
    { id: "D17", name: "透明深蓝", hex: "#5B88C0" },
    { id: "D18", name: "珠光蓝", hex: "#7898C0" },
    { id: "D19", name: "闪光蓝", hex: "#3878D0" },
    { id: "D20", name: "闪光深蓝", hex: "#2050A0" },
    { id: "D21", name: "深蓝紫", hex: "#4A2C8A" },
    { id: "D22", name: "薰衣草", hex: "#B39DDB" },
    { id: "D23", name: "淡丁香", hex: "#DCD0FF" },
    { id: "D24", name: "夜光白", hex: "#F0F0E0" },
    { id: "D25", name: "夜光黄", hex: "#F8F0B0" },
    { id: "D26", name: "夜光绿", hex: "#D0F0C0" },

    // ==========================================
    //  E 系列 · 粉玫系（E01 ~ E24）
    // ==========================================
    { id: "E01", name: "浅粉", hex: "#FCE4EC" },
    { id: "E02", name: "粉色", hex: "#F8BBD0" },
    { id: "E03", name: "玫粉", hex: "#F48FB1" },
    { id: "E04", name: "桃粉", hex: "#EC407A" },
    { id: "E05", name: "玫红", hex: "#C2185B" },
    { id: "E06", name: "暗粉", hex: "#AD1457" },
    { id: "E07", name: "浅紫", hex: "#E1BEE7" },
    { id: "E08", name: "淡紫", hex: "#CE93D8" },
    { id: "E09", name: "紫色", hex: "#AB47BC" },
    { id: "E10", name: "深紫", hex: "#7B1FA2" },
    { id: "E11", name: "葡紫", hex: "#4A148C" },
    { id: "E12", name: "丁香紫", hex: "#CDA4DE" },
    { id: "E13", name: "蓝紫", hex: "#8A2BE2" },
    { id: "E14", name: "樱花粉", hex: "#FFB7C5" },
    { id: "E15", name: "烟粉", hex: "#DCBAB5" },
    { id: "E16", name: "藕粉", hex: "#D4A0A0" },
    { id: "E17", name: "婴儿粉", hex: "#FFD6E0" },
    { id: "E18", name: "樱桃粉", hex: "#FFB2C1" },
    { id: "E19", name: "浅玫瑰", hex: "#FFE4E1" },
    { id: "E20", name: "薰衣草粉", hex: "#E8D0E8" },
    { id: "E21", name: "荧光粉", hex: "#FF69B4" },
    { id: "E22", name: "荧光玫红", hex: "#FF1493" },
    { id: "E23", name: "荧光紫", hex: "#BF00FF" },
    { id: "E24", name: "荧光桃粉", hex: "#FF6EB4" },

    // ==========================================
    //  F 系列 · 红色系（F01 ~ F25）
    // ==========================================
    { id: "F01", name: "珊瑚", hex: "#FF8A80" },
    { id: "F02", name: "正红", hex: "#D32F2F" },
    { id: "F03", name: "深红", hex: "#B71C1C" },
    { id: "F04", name: "酒红", hex: "#880E4F" },
    { id: "F05", name: "铁锈红", hex: "#B7410E" },
    { id: "F06", name: "砖红", hex: "#CB4154" },
    { id: "F07", name: "番茄红", hex: "#FF6347" },
    { id: "F08", name: "西瓜红", hex: "#FC6C85" },
    { id: "F09", name: "胭脂", hex: "#D43D56" },
    { id: "F10", name: "浅珊瑚", hex: "#FFB4A2" },
    { id: "F11", name: "豆沙", hex: "#B5848E" },
    { id: "F12", name: "深酒红", hex: "#722F37" },
    { id: "F13", name: "暗红", hex: "#8B0000" },
    { id: "F14", name: "深玫红", hex: "#8B0A50" },
    { id: "F15", name: "紫红", hex: "#702963" },
    { id: "F16", name: "暗紫", hex: "#51186A" },
    { id: "F17", name: "荧光红", hex: "#FF2400" },
    { id: "F18", name: "荧光橘红", hex: "#FF4500" },
    { id: "F19", name: "荧光珊瑚", hex: "#FF6F61" },
    { id: "F20", name: "透明红", hex: "#FF7B7B" },
    { id: "F21", name: "透明深红", hex: "#D46A6A" },
    { id: "F22", name: "透明粉", hex: "#FFB6C8" },
    { id: "F23", name: "透明玫红", hex: "#E88BA8" },
    { id: "F24", name: "闪光红", hex: "#E03030" },
    { id: "F25", name: "闪光粉", hex: "#F090A8" },

    // ==========================================
    //  G 系列 · 棕肤系（G01 ~ G21）
    // ==========================================
    { id: "G01", name: "浅棕", hex: "#D7CCC8" },
    { id: "G02", name: "卡其", hex: "#BCAAA4" },
    { id: "G03", name: "棕色", hex: "#8D6E63" },
    { id: "G04", name: "深棕", hex: "#5D4037" },
    { id: "G05", name: "咖啡", hex: "#3E2723" },
    { id: "G06", name: "肤色", hex: "#FFCCBC" },
    { id: "G07", name: "深肤", hex: "#E0A68C" },
    { id: "G08", name: "驼色", hex: "#C19A6B" },
    { id: "G09", name: "栗色", hex: "#954535" },
    { id: "G10", name: "奶茶色", hex: "#D2B48C" },
    { id: "G11", name: "浅驼", hex: "#DEB887" },
    { id: "G12", name: "巧克力", hex: "#462113" },
    { id: "G13", name: "深栗", hex: "#4E2728" },
    { id: "G14", name: "黑咖", hex: "#2E1F11" },
    { id: "G15", name: "透明棕", hex: "#C8A878" },
    { id: "G16", name: "闪光棕", hex: "#886040" },
    { id: "G17", name: "珠光金", hex: "#D4AF37" },
    { id: "G18", name: "金属金", hex: "#CFB53B" },
    { id: "G19", name: "金属铜", hex: "#B87333" },
    { id: "G20", name: "玫瑰金", hex: "#B76E79" },
    { id: "G21", name: "珠光香槟", hex: "#DDD0B8" },

    // ==========================================
    //  H 系列 · 黑白灰系（H01 ~ H23）
    // ==========================================
    { id: "H01", name: "浅灰", hex: "#E0E0E0" },
    { id: "H02", name: "灰色", hex: "#9E9E9E" },
    { id: "H03", name: "深灰", hex: "#616161" },
    { id: "H04", name: "黑色", hex: "#212121" },
    { id: "H05", name: "银灰", hex: "#C0C0C0" },
    { id: "H06", name: "珍珠灰", hex: "#D8D4CF" },
    { id: "H07", name: "暖白", hex: "#F8F0EB" },
    { id: "H08", name: "炭灰", hex: "#4E4E50" },
    { id: "H09", name: "烟灰", hex: "#848482" },
    { id: "H10", name: "铁灰", hex: "#434B4D" },
    { id: "H11", name: "石墨灰", hex: "#383838" },
    { id: "H12", name: "闪光黑", hex: "#303038" },
    { id: "H13", name: "珠光银", hex: "#BCC6CC" },
    { id: "H14", name: "金属银", hex: "#AAB2B5" },
    { id: "H15", name: "透明灰", hex: "#B8B8B8" },
    { id: "H16", name: "透明烟灰", hex: "#888888" },
    { id: "H17", name: "闪光金", hex: "#FFD700" },
    { id: "H18", name: "闪光黄", hex: "#F0D020" },
    { id: "H19", name: "夜光粉", hex: "#F8D0D8" },
    { id: "H20", name: "夜光橙", hex: "#F8D8B0" },
    { id: "H21", name: "夜光紫", hex: "#D8C8E8" },
    { id: "H22", name: "夜光黄绿", hex: "#D8F0A0" },
    { id: "H23", name: "象牙白", hex: "#F5F0DC" },

    // ==========================================
    //  M 系列 · 大地色系（M01 ~ M15）
    // ==========================================
    { id: "M01", name: "大地棕", hex: "#A0826D" },
    { id: "M02", name: "大地黄", hex: "#C8A96E" },
    { id: "M03", name: "大地绿", hex: "#7A8B6E" },
    { id: "M04", name: "大地灰", hex: "#8A8680" },
    { id: "M05", name: "大地橘", hex: "#C0845E" },
    { id: "M06", name: "沙色", hex: "#D4C4A8" },
    { id: "M07", name: "泥土色", hex: "#9B7653" },
    { id: "M08", name: "亚麻色", hex: "#C8B99A" },
    { id: "M09", name: "陶土色", hex: "#B06840" },
    { id: "M10", name: "枯叶色", hex: "#A68B5B" },
    { id: "M11", name: "苔藓色", hex: "#6B7F56" },
    { id: "M12", name: "石灰色", hex: "#B0ACA0" },
    { id: "M13", name: "朽木色", hex: "#7D6850" },
    { id: "M14", name: "暮色", hex: "#8E7B6E" },
    { id: "M15", name: "大地红", hex: "#A05040" },

    // ==========================================
    //  闪光/珠光补充（归入对应系列中已包含）
    //  透明色补充（归入对应系列中已包含）
    //  夜光色补充（归入对应系列中已包含）
    // ==========================================
];
