// palette.js — Mard 拼豆色板数据（221色）
// 按 Mard 官方色卡分组：A黄橙26色 B绿色32色 C蓝青29色 D蓝紫26色
// E粉玫24色 F红色25色 G棕肤21色 H黑白灰23色 M大地15色
// hex 值为近似参考色，请以实物色卡为准

const MARD_PALETTE = [
    // ==========================================
    //  A 系列 · 黄橙系（A01 ~ A26）
    // ==========================================
    { id: "A01", name: "奶油黄", hex: "#FAF4C8" },
    { id: "A02", name: "鹅黄", hex: "#FFFFD5" },
    { id: "A03", name: "向日葵", hex: "#FFEF8B" },
    { id: "A04", name: "柠黄", hex: "#FBED56" },
    { id: "A05", name: "明黄", hex: "#F4D738" },
    { id: "A06", name: "杏橙", hex: "#FEAC4C" },
    { id: "A07", name: "蜜桃粉", hex: "#FEB8AC" },
    { id: "A08", name: "金盏花", hex: "#FFDA45" },
    { id: "A09", name: "橘黄", hex: "#FF995B" },
    { id: "A10", name: "活力橙", hex: "#F77C31" },
    { id: "A11", name: "暖杏", hex: "#FFDD99" },
    { id: "A12", name: "蜜瓜橙", hex: "#FE9F72" },
    { id: "A13", name: "琥珀金", hex: "#FFC365" },
    { id: "A14", name: "火焰红", hex: "#FD543D" },
    { id: "A15", name: "柠檬光", hex: "#FFF365" },
    { id: "A16", name: "浅黄", hex: "#FFFF9F" },
    { id: "A17", name: "芒果黄", hex: "#FFE36E" },
    { id: "A18", name: "蜂蜜色", hex: "#FEBE7D" },
    { id: "A19", name: "西瓜粉", hex: "#FD7C72" },
    { id: "A20", name: "金麦色", hex: "#FFD568" },
    { id: "A21", name: "香草黄", hex: "#FFE395" },
    { id: "A22", name: "青柠黄", hex: "#F4F57D" },
    { id: "A23", name: "奶茶米", hex: "#E6C9B7" },
    { id: "A24", name: "月光黄", hex: "#F7F8A2" },
    { id: "A25", name: "蜜糖金", hex: "#FFD67D" },
    { id: "A26", name: "橙金", hex: "#FFC830" },

    // ==========================================
    //  B 系列 · 绿色系（B01 ~ B32）
    // ==========================================
    { id: "B01", name: "荧光黄绿", hex: "#E6EE31" },
    { id: "B02", name: "荧光绿", hex: "#63F347" },
    { id: "B03", name: "嫩芽绿", hex: "#9EF780" },
    { id: "B04", name: "草绿", hex: "#5DE035" },
    { id: "B05", name: "翡翠绿", hex: "#35E352" },
    { id: "B06", name: "薄荷绿", hex: "#65E2A6" },
    { id: "B07", name: "翠湖绿", hex: "#3DAF80" },
    { id: "B08", name: "松石绿", hex: "#1C9C4F" },
    { id: "B09", name: "墨绿", hex: "#27523A" },
    { id: "B10", name: "薄荷冰", hex: "#95D3C2" },
    { id: "B11", name: "橄榄绿", hex: "#5D722A" },
    { id: "B12", name: "森林绿", hex: "#166F41" },
    { id: "B13", name: "柠绿", hex: "#CAEB7B" },
    { id: "B14", name: "青苹果", hex: "#ADE946" },
    { id: "B15", name: "深松绿", hex: "#2E5132" },
    { id: "B16", name: "浅草绿", hex: "#C5ED9C" },
    { id: "B17", name: "抹茶色", hex: "#9BB13A" },
    { id: "B18", name: "鹦鹉绿", hex: "#E6EE49" },
    { id: "B19", name: "碧玉绿", hex: "#24B88C" },
    { id: "B20", name: "奶绿", hex: "#C2F0CC" },
    { id: "B21", name: "孔雀绿", hex: "#156A6B" },
    { id: "B22", name: "深海松", hex: "#0B3C43" },
    { id: "B23", name: "暗苔绿", hex: "#303A21" },
    { id: "B24", name: "蜜瓜绿", hex: "#EEFCA5" },
    { id: "B25", name: "苍松色", hex: "#4E846D" },
    { id: "B26", name: "苔藓棕", hex: "#8D7A35" },
    { id: "B27", name: "春芽色", hex: "#CCE1AF" },
    { id: "B28", name: "冰薄荷", hex: "#9EE5B9" },
    { id: "B29", name: "黄绿", hex: "#C5E254" },
    { id: "B30", name: "浅抹茶", hex: "#E2FCB1" },
    { id: "B31", name: "嫩绿色", hex: "#B0E792" },
    { id: "B32", name: "青橄榄", hex: "#9CAB5A" },

    // ==========================================
    //  C 系列 · 蓝青系（C01 ~ C29）
    // ==========================================
    { id: "C01", name: "薄荷白", hex: "#E8FFE7" },
    { id: "C02", name: "冰晶蓝", hex: "#A9F9FC" },
    { id: "C03", name: "浅天蓝", hex: "#A0E2FB" },
    { id: "C04", name: "晴空蓝", hex: "#41CCFF" },
    { id: "C05", name: "湖蓝", hex: "#01ACEB" },
    { id: "C06", name: "矢车菊蓝", hex: "#50AAF0" },
    { id: "C07", name: "钴蓝", hex: "#3677D2" },
    { id: "C08", name: "宝蓝", hex: "#0F54C0" },
    { id: "C09", name: "皇家蓝", hex: "#324BCA" },
    { id: "C10", name: "绿松石蓝", hex: "#3EBCE2" },
    { id: "C11", name: "孔雀蓝", hex: "#28DDDE" },
    { id: "C12", name: "深海蓝", hex: "#1C334D" },
    { id: "C13", name: "冰蓝", hex: "#CDE8FF" },
    { id: "C14", name: "水晶蓝", hex: "#D5FDFF" },
    { id: "C15", name: "碧海蓝", hex: "#22C4C6" },
    { id: "C16", name: "深蓝", hex: "#1557A8" },
    { id: "C17", name: "荧光蓝", hex: "#04D1F6" },
    { id: "C18", name: "墨蓝", hex: "#1D3344" },
    { id: "C19", name: "深青蓝", hex: "#1887A2" },
    { id: "C20", name: "海军蓝", hex: "#176DAF" },
    { id: "C21", name: "婴儿蓝", hex: "#BEDDFF" },
    { id: "C22", name: "雾霾蓝", hex: "#67B4BE" },
    { id: "C23", name: "粉蓝", hex: "#C8E2FF" },
    { id: "C24", name: "天空蓝", hex: "#7CC4FF" },
    { id: "C25", name: "薄荷蓝", hex: "#A9E5E5" },
    { id: "C26", name: "蔚蓝", hex: "#3CAED8" },
    { id: "C27", name: "淡蓝紫", hex: "#D3DFFA" },
    { id: "C28", name: "雾蓝", hex: "#BBCFED" },
    { id: "C29", name: "藏青", hex: "#34488E" },

    // ==========================================
    //  D 系列 · 蓝紫系（D01 ~ D26）
    // ==========================================
    { id: "D01", name: "浅蓝紫", hex: "#AEB4F2" },
    { id: "D02", name: "鸢尾紫", hex: "#858EDD" },
    { id: "D03", name: "深靛蓝", hex: "#2F54AF" },
    { id: "D04", name: "午夜蓝", hex: "#182A84" },
    { id: "D05", name: "亮紫", hex: "#B843C5" },
    { id: "D06", name: "薰衣草紫", hex: "#AC7BDE" },
    { id: "D07", name: "葡萄紫", hex: "#8854B3" },
    { id: "D08", name: "淡丁香", hex: "#E2D3FF" },
    { id: "D09", name: "丁香紫", hex: "#D5B9F8" },
    { id: "D10", name: "暗紫", hex: "#361851" },
    { id: "D11", name: "雾蓝紫", hex: "#B9BAE1" },
    { id: "D12", name: "粉兰花", hex: "#DE9AD4" },
    { id: "D13", name: "洋玫紫", hex: "#B90095" },
    { id: "D14", name: "深紫", hex: "#8B279B" },
    { id: "D15", name: "靛紫", hex: "#2F1F90" },
    { id: "D16", name: "月白紫", hex: "#E3E1EE" },
    { id: "D17", name: "浅蓝灰", hex: "#C4D4F6" },
    { id: "D18", name: "风铃紫", hex: "#A45EC7" },
    { id: "D19", name: "藕荷色", hex: "#D8C3D7" },
    { id: "D20", name: "玫瑰紫", hex: "#9C32B2" },
    { id: "D21", name: "紫罗兰", hex: "#9A009B" },
    { id: "D22", name: "皇家紫", hex: "#333A95" },
    { id: "D23", name: "浅紫云", hex: "#EBDAFC" },
    { id: "D24", name: "矢车菊紫", hex: "#7786E5" },
    { id: "D25", name: "蓝紫", hex: "#494FC7" },
    { id: "D26", name: "淡紫霞", hex: "#DFC2F8" },

    // ==========================================
    //  E 系列 · 粉玫系（E01 ~ E24）
    // ==========================================
    { id: "E01", name: "蜜桃粉", hex: "#FDD3CC" },
    { id: "E02", name: "粉霞", hex: "#FEC0DF" },
    { id: "E03", name: "樱花粉", hex: "#FFB7E7" },
    { id: "E04", name: "玫瑰红", hex: "#E8649E" },
    { id: "E05", name: "荧光桃红", hex: "#F551A2" },
    { id: "E06", name: "火烈鸟", hex: "#F13D74" },
    { id: "E07", name: "深玫红", hex: "#C63478" },
    { id: "E08", name: "婴儿粉", hex: "#FFDDE9" },
    { id: "E09", name: "兰花紫", hex: "#E970CC" },
    { id: "E10", name: "紫玫红", hex: "#D33793" },
    { id: "E11", name: "浅珊瑚", hex: "#FCDDD2" },
    { id: "E12", name: "粉丁香", hex: "#F78FC3" },
    { id: "E13", name: "深玫瑰", hex: "#B5006D" },
    { id: "E14", name: "杏粉", hex: "#FFD1BA" },
    { id: "E15", name: "浅粉", hex: "#F8C7C9" },
    { id: "E16", name: "奶白粉", hex: "#FFF3EB" },
    { id: "E17", name: "樱粉", hex: "#FFE2EA" },
    { id: "E18", name: "糖果粉", hex: "#FFC7DB" },
    { id: "E19", name: "少女粉", hex: "#FEBAD5" },
    { id: "E20", name: "灰粉紫", hex: "#D8C7D1" },
    { id: "E21", name: "烟灰粉", hex: "#BD9DA1" },
    { id: "E22", name: "藕紫", hex: "#B785A1" },
    { id: "E23", name: "暮烟紫", hex: "#937A8D" },
    { id: "E24", name: "淡紫粉", hex: "#E1BCE8" },

    // ==========================================
    //  F 系列 · 红色系（F01 ~ F25）
    // ==========================================
    { id: "F01", name: "珊瑚橙", hex: "#FD957B" },
    { id: "F02", name: "正红", hex: "#FC3D46" },
    { id: "F03", name: "烈焰红", hex: "#F74941" },
    { id: "F04", name: "猩红", hex: "#FC283C" },
    { id: "F05", name: "深红", hex: "#E7002F" },
    { id: "F06", name: "酒红", hex: "#943630" },
    { id: "F07", name: "暗酒红", hex: "#971937" },
    { id: "F08", name: "胭脂红", hex: "#BC0028" },
    { id: "F09", name: "玫瑰粉", hex: "#E2677A" },
    { id: "F10", name: "赤棕", hex: "#8A4526" },
    { id: "F11", name: "栗红", hex: "#5A2121" },
    { id: "F12", name: "桃红", hex: "#FD4E6A" },
    { id: "F13", name: "柿红", hex: "#F35744" },
    { id: "F14", name: "浅珊瑚粉", hex: "#FFA9AD" },
    { id: "F15", name: "大红", hex: "#D30022" },
    { id: "F16", name: "蜜桃色", hex: "#FEC2A6" },
    { id: "F17", name: "烟霞色", hex: "#E69C79" },
    { id: "F18", name: "陶土橙", hex: "#D37C46" },
    { id: "F19", name: "砖红", hex: "#C1444A" },
    { id: "F20", name: "藕粉红", hex: "#CD9391" },
    { id: "F21", name: "樱花瓣", hex: "#F7B4C6" },
    { id: "F22", name: "柔粉", hex: "#FDC0D0" },
    { id: "F23", name: "番茄红", hex: "#F67E66" },
    { id: "F24", name: "玫瑰灰", hex: "#E698AA" },
    { id: "F25", name: "石榴红", hex: "#E54B4F" },

    // ==========================================
    //  G 系列 · 棕肤系（G01 ~ G21）
    // ==========================================
    { id: "G01", name: "奶油肤", hex: "#FFE2CE" },
    { id: "G02", name: "杏肤色", hex: "#FFCAAA" },
    { id: "G03", name: "浅肤", hex: "#F4C3A5" },
    { id: "G04", name: "驼色", hex: "#E1B383" },
    { id: "G05", name: "焦糖金", hex: "#EDB045" },
    { id: "G06", name: "琥珀黄", hex: "#E99C17" },
    { id: "G07", name: "棕褐", hex: "#9D5B3E" },
    { id: "G08", name: "深栗色", hex: "#753832" },
    { id: "G09", name: "沙棕", hex: "#E6B483" },
    { id: "G10", name: "蜂蜜棕", hex: "#D98C39" },
    { id: "G11", name: "麦芽色", hex: "#E0C593" },
    { id: "G12", name: "暖杏色", hex: "#FFC890" },
    { id: "G13", name: "赤铜棕", hex: "#B7714A" },
    { id: "G14", name: "咖啡棕", hex: "#8D614C" },
    { id: "G15", name: "米白", hex: "#FCF9E0" },
    { id: "G16", name: "浅驼色", hex: "#F2D9BA" },
    { id: "G17", name: "深咖棕", hex: "#78524B" },
    { id: "G18", name: "奶白杏", hex: "#FFE4CC" },
    { id: "G19", name: "橙棕", hex: "#E07935" },
    { id: "G20", name: "焦棕", hex: "#A94023" },
    { id: "G21", name: "核桃棕", hex: "#B88558" },

    // ==========================================
    //  H 系列 · 黑白灰系（H01 ~ H23）
    // ==========================================
    { id: "H01", name: "月白", hex: "#FDFBFF" },
    { id: "H02", name: "纯白", hex: "#FEFFFF" },
    { id: "H03", name: "银灰", hex: "#B6B1BA" },
    { id: "H04", name: "灰色", hex: "#89858C" },
    { id: "H05", name: "深灰", hex: "#48464E" },
    { id: "H06", name: "炭灰", hex: "#2F2B2F" },
    { id: "H07", name: "黑色", hex: "#000000" },
    { id: "H08", name: "灰粉", hex: "#E7D6DB" },
    { id: "H09", name: "浅灰", hex: "#EDEDED" },
    { id: "H10", name: "暖灰", hex: "#EEE9EA" },
    { id: "H11", name: "淡灰蓝", hex: "#CECDD5" },
    { id: "H12", name: "奶白色", hex: "#FFF5ED" },
    { id: "H13", name: "象牙黄", hex: "#F5ECD2" },
    { id: "H14", name: "薄荷灰", hex: "#CFD7D3" },
    { id: "H15", name: "青灰", hex: "#98A6A8" },
    { id: "H16", name: "墨色", hex: "#1D1414" },
    { id: "H17", name: "珍珠白", hex: "#F1EDED" },
    { id: "H18", name: "暖白", hex: "#FFFDF0" },
    { id: "H19", name: "亚麻白", hex: "#F6EFE2" },
    { id: "H20", name: "石灰蓝", hex: "#949FA3" },
    { id: "H21", name: "柠檬白", hex: "#FFFBE1" },
    { id: "H22", name: "雾灰", hex: "#CACAD4" },
    { id: "H23", name: "橄榄灰", hex: "#9A9D94" },

    // ==========================================
    //  M 系列 · 大地色系（M01 ~ M15）
    // ==========================================
    { id: "M01", name: "灰松绿", hex: "#BCC6B8" },
    { id: "M02", name: "苔原绿", hex: "#8AA386" },
    { id: "M03", name: "雾岩灰", hex: "#697D80" },
    { id: "M04", name: "沙米色", hex: "#E3D2BC" },
    { id: "M05", name: "亚麻色", hex: "#D0CCAA" },
    { id: "M06", name: "枯叶色", hex: "#B0A782" },
    { id: "M07", name: "灰驼色", hex: "#B4A497" },
    { id: "M08", name: "暮烟粉", hex: "#B38281" },
    { id: "M09", name: "沙棕色", hex: "#A58767" },
    { id: "M10", name: "藕紫灰", hex: "#C5B2BC" },
    { id: "M11", name: "梅紫", hex: "#9F7594" },
    { id: "M12", name: "深豆沙", hex: "#644749" },
    { id: "M13", name: "赤陶", hex: "#D19066" },
    { id: "M14", name: "红陶", hex: "#C77362" },
    { id: "M15", name: "苍绿灰", hex: "#757D78" },
];
